### PR TITLE
Adjust prefpane width to 668

### PR DESCRIPTION
**Pull request by stevenlei**
I was wondering why there is a space on the right:

image

I thought it was because of the size, we are trying to fit the width of the system prefpane. But finally I have found this from the Apple docs, although it is a bit old:

https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PreferencePanes/Concepts/Application.html
> The System Preferences window has a fixed width (668 pixels) but resizes itself vertically to fit the size of the current preference pane.

So I adjusted it:
- Resized the window to 668 width
- Added a leading and trailing constraint to the masthead box without a fixed value
- Set the width of the masthead box to >= 450

Then it becomes:
image

Feel free to comment if it looks too wide or if it is okay.

### CODE REVIEW

**Comment by mxcl** [comment]
I sized it per the new System Settings width, and then discovered that third party prefpanes are loaded with the pre-redesign widths (for compatibility reasons presumably).

I had hoped we'd figure out how to ask System Settings to use the new width, but seemingly that isn’t possible.

Our design is per the new-design styling, which means this expanded width looks a bit odd. I tried to get us to be centered horizontally, but failed at that attempt.

Dunno. Will think about if we should merge this. Thanks for the PR!

**Comment by stevenlei** [comment]
Yes I can't find a way to get the width from System Settings either.

You said to centre it horizontally, do you mean this:
image

By updating the window width to 668, the layout is now properly centered.

Maybe we can go for this approach for now, and if there will be official responsive layout support from Apple in future, which would likely come with proper APIs, we can implement that after?

**Comment by mxcl** [comment]
yes centered looks good.

**Comment by stevenlei** [comment]
Ok I will close this PR and create another one for that

**Pull request closed without merging**
